tasmoadmin:
  container_name: tasmoadmin
  image: raymondmm/tasmoadmin
  restart: unless-stopped
  ports:
    - "8088:80"
  x-homer-port: "8088"
  volumes:
    - ./volumes/tasmoadmin/data:/data
  networks:
    - iotstack_nw

